import { professionalProfile, siteUrl } from "@/lib/site";

const wa="https://wa.me/5513974078084?text=Ol%C3%A1%2C%20Dra.%20Carolina.%20Vim%20pelo%20site%20e%20gostaria%20de%20informa%C3%A7%C3%B5es%20sobre%20o%20atendimento%20jur%C3%ADdico.";
const Arrow=()=> <span aria-hidden="true">→</span>;
export default function Home(){return <main>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({
    "@context":"https://schema.org",
    "@type":"LegalService",
    name:professionalProfile.name,
    url:siteUrl,
    telephone:professionalProfile.phone,
    email:professionalProfile.email,
    address:{"@type":"PostalAddress",streetAddress:"Avenida Pedro Lessa, 2706, sala 13",addressLocality:"Santos",addressRegion:"SP",postalCode:"11025-002",addressCountry:"BR"},
    sameAs:professionalProfile.sameAs
  }).replace(/</g,"\\u003c")}} />
  <header><a className="brand" href="#inicio"><b>CMM</b><span>Carolina Marques Mendes<small>Advocacia · OAB/SP 296.392</small></span></a><nav><a href="#sobre">A advogada</a><a href="#proposito">Propósito</a><a href="#atendimento">Atendimento</a><a href="#contato">Contato</a></nav><a className="headCta" href={wa} target="_blank" rel="noreferrer">Conversar <Arrow/></a></header>
  <section className="hero" id="inicio"><div className="copy"><p className="eyebrow">ADVOCACIA EM SANTOS · SP</p><h1>Escuta para compreender.<em>Clareza para orientar.</em></h1><p className="lead">Atendimento jurídico individualizado, com análise técnica, comunicação transparente e responsabilidade em cada etapa.</p><div className="actions"><a className="button gold" href={wa} target="_blank" rel="noreferrer">Conversar com a Dra. Carolina <Arrow/></a><a href="#atendimento">Conheça o atendimento</a></div><small>O contato será aberto no WhatsApp.</small></div><div className="seal" aria-hidden="true">CMM</div></section>
  <section className="split light" id="sobre"><div><p className="eyebrow">PRESENÇA PROFISSIONAL</p><h2>Uma advocacia feita de técnica, humanidade e consciência.</h2></div><div className="body"><p className="large">A Dra. Carolina Marques Mendes conduz cada atendimento com escuta respeitosa, independência profissional e rigor técnico.</p><p>Antes de qualquer estratégia, existe uma história que precisa ser compreendida. O atendimento parte da realidade de cada pessoa, apresenta os caminhos juridicamente possíveis e preserva a transparência ao longo da atuação.</p><p className="id">CAROLINA MARQUES MENDES <span>OAB/SP 296.392</span></p></div></section>
  <section className="split navy" id="proposito"><div><p className="eyebrow">ADVOCACIA COM PROPÓSITO</p><h2>A presença da mulher também transforma a Justiça.</h2></div><div className="body"><p>A participação feminina na advocacia brasileira representa conquista de espaço, autonomia, liderança responsável e contribuição essencial para uma Justiça mais plural e consciente.</p><p>Como mulher e advogada, Carolina exerce seu ofício com preparação, independência e responsabilidade — sem perder de vista a dimensão humana de cada questão.</p><blockquote>“Técnica para orientar. Coragem para atuar. Responsabilidade para representar.”</blockquote></div></section>
  <section className="values light"><p className="eyebrow">PRINCÍPIOS EM PRÁTICA</p><h2>O que orienta cada atendimento.</h2><div className="cards"><article><span>MISSÃO</span><h3>Atender com clareza</h3><p>Atendimento jurídico individualizado, tecnicamente responsável e atento à realidade de cada pessoa.</p></article><article><span>VISÃO</span><h3>Humanizar sem perder o rigor</h3><p>Contribuir para uma advocacia mais acessível, igualitária e consciente de sua responsabilidade social.</p></article><article><span>VALORES</span><h3>Ética como fundamento</h3><p>Independência, escuta, transparência, igualdade, sigilo, respeito e responsabilidade profissional.</p></article></div></section>
  <section className="process" id="atendimento"><div><p className="eyebrow">COMO FUNCIONA</p><h2>Um primeiro contato simples e respeitoso.</h2><p>O envio de uma mensagem permite solicitar informações iniciais. A análise jurídica depende da compreensão dos fatos e documentos de cada situação.</p></div><ol><li><b>01</b><span><strong>Contato inicial</strong>Apresente brevemente o assunto e informe seu nome.</span></li><li><b>02</b><span><strong>Compreensão da situação</strong>Serão esclarecidas as informações necessárias para prosseguir.</span></li><li><b>03</b><span><strong>Orientação dos próximos passos</strong>Os caminhos possíveis são apresentados de forma clara.</span></li></ol><a className="button gold" href={wa} target="_blank" rel="noreferrer">Iniciar uma conversa <Arrow/></a></section>
  <section className="contact light" id="contato"><div><p className="eyebrow">CONTATO PROFISSIONAL</p><h2>Vamos conversar com clareza sobre sua necessidade?</h2><p>Entre em contato para receber informações sobre o atendimento jurídico e os próximos passos possíveis.</p><a className="button dark" href={wa} target="_blank" rel="noreferrer">Falar com a Dra. Carolina <Arrow/></a></div><address><span><b>ESCRITÓRIO</b>Avenida Pedro Lessa, 2706, sala 13<br/>Embaré · Santos/SP · CEP 11025-002</span><span><b>TELEFONE E WHATSAPP</b><a href="tel:+551333492095">(13) 3349-2095</a><a href={wa} target="_blank" rel="noreferrer">(13) 97407-8084</a></span><span><b>E-MAIL</b><a href="mailto:carolmmendesadv@gmail.com">carolmmendesadv@gmail.com</a></span><span><b>REDES PROFISSIONAIS</b><a href="https://www.instagram.com/dra.carolmarquesmendes/" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.facebook.com/dra.carolmarquesmendes" target="_blank" rel="noreferrer">Facebook</a></span></address></section>
  <footer><span>Carolina Marques Mendes · OAB/SP 296.392</span><span>Conteúdo institucional e informativo. O contato não estabelece automaticamente relação cliente-advogada. <a href="/privacidade">Política de Privacidade</a></span><span>© 2026</span></footer>
  <a className="float" href={wa} target="_blank" rel="noreferrer" aria-label="Falar diretamente com a Dra. Carolina pelo WhatsApp">WhatsApp</a>
</main>}
